# Generated by Django 3.2.6 on 2021-09-10 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('StaffName', models.CharField(max_length=50, null=True)),
                ('StaffMobileNumber', models.BigIntegerField(blank=True, null=True)),
                ('Designation', models.CharField(blank=True, choices=[('Designation', 'Please Select Designation'), ('Tech-3', 'Tech-3'), ('Tech-2', 'Tech-2'), ('Tech-1', 'Tech-1'), ('Sr.Tech', 'Sr.Tech'), ('MCM', 'MCM')], default='Tech-3', max_length=30, null=True)),
                ('StaffAddress', models.CharField(max_length=150, null=True)),
                ('DateOfJoining', models.DateField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GangName', models.CharField(default='Error', max_length=100, unique=True)),
                ('Date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('M1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='M1', to='staff.staff')),
                ('M10', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='M10', to='staff.staff')),
                ('M2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='M2', to='staff.staff')),
                ('M3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='M3', to='staff.staff')),
                ('M4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='M4', to='staff.staff')),
                ('M5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='M5', to='staff.staff')),
                ('M6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='M6', to='staff.staff')),
                ('M7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='M7', to='staff.staff')),
                ('M8', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='M8', to='staff.staff')),
                ('M9', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='M9', to='staff.staff')),
            ],
        ),
    ]
