# Generated by Django 3.2.6 on 2021-09-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='StaffToken',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
