# Generated by Django 3.2.6 on 2021-08-28 09:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleRecieved',
            fields=[
                ('Serial', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('RakeNumber', models.CharField(max_length=50, null=True)),
                ('BPC_Number', models.BigIntegerField(null=True)),
                ('LineNumber', models.CharField(blank=True, choices=[('SELECTLINE', 'Please Select Examination Line'), ('NH1', 'NH1'), ('NH2', 'NH2'), ('NH4', 'NH4'), ('NH5', 'NH5'), ('NH6', 'NH6'), ('NH7', 'NH7'), ('NH8', 'NH8')], default='SELECTLINE', max_length=10, null=True)),
                ('ModuleName', models.CharField(max_length=20, null=True)),
                ('Wagon1Number', models.BigIntegerField(blank=True, null=True)),
                ('Wagon1Type', models.CharField(blank=True, choices=[('SelectWagon', 'Please Select Wagon Type'), ('BOXN', 'BOXN'), ('BOXNHA', 'BOXNHA'), ('BOXNHS', 'BOXNHS'), ('BOXNCR', 'BOXNCR'), ('BOXNLW', 'BOXNLW'), ('BOXNB', 'BOXNB'), ('BOXNF', 'BOXNF'), ('BOXNG', 'BOXNG'), ('BOY', 'BOY'), ('BOST', 'BOST'), ('BOXNAL', 'BOXNAL'), ('BOSTHS', 'BOSTHS'), ('BOXNHL', 'BOXNHL'), ('BOXNAL', 'BOXNAL'), ('BOXNS', 'BOXNS'), ('BCN', 'BCN'), ('BCNA', 'BCNA'), ('BCNAHS', 'BCNAHS'), ('BCCNR', 'BCCNR'), ('BTPN', 'BTPN'), ('BTPNHS', 'BTPNHS'), ('BTPGLN', 'BTPGLN'), ('BTALN', 'BTALN'), ('BTCS', 'BTCS'), ('BTPH', 'BTPH'), ('BTAP', 'BTAP'), ('BTFLN', 'BTFLN'), ('BRNA', 'BRNA'), ('BRNAHS', 'BRNAHS'), ('BFNS', 'BFNS'), ('BOMN', 'BOMN'), ('BRSTH', 'BRSTH'), ('BFAT', 'BFAT'), ('BLCA', 'BLCA'), ('BLCB', 'BLCB'), ('BLLA', 'BLLA'), ('BLLB', 'BLLB'), ('BRS', 'BRS'), ('BFU', 'BFU'), ('BRHNEHS', 'BRHNEHS'), ('BCL', 'BCL'), ('BCLA', 'BCLA'), ('BOBYN', 'BOBYN'), ('BOBYNHS', 'BOBYNHS'), ('BOBRN', 'BOBRN'), ('BOBRNHS', 'BOBRNHS'), ('BOBRAL', 'BOBRAL'), ('BOBSN', 'BOBSN'), ('BWTB', 'BWTB'), ('MBWT', 'MBWT'), ('DBKM', 'DBKM'), ('MBWZ', 'MBWZ'), ('BVZC', 'BVZC'), ('BVZI', 'BVZI'), ('BFKHN', 'BFKHN')], default='SelectWagon', max_length=11, null=True)),
                ('Wagon2Number', models.BigIntegerField(blank=True, null=True)),
                ('Wagon2Type', models.CharField(blank=True, choices=[('SelectWagon', 'Please Select Wagon Type'), ('BOXN', 'BOXN'), ('BOXNHA', 'BOXNHA'), ('BOXNHS', 'BOXNHS'), ('BOXNCR', 'BOXNCR'), ('BOXNLW', 'BOXNLW'), ('BOXNB', 'BOXNB'), ('BOXNF', 'BOXNF'), ('BOXNG', 'BOXNG'), ('BOY', 'BOY'), ('BOST', 'BOST'), ('BOXNAL', 'BOXNAL'), ('BOSTHS', 'BOSTHS'), ('BOXNHL', 'BOXNHL'), ('BOXNAL', 'BOXNAL'), ('BOXNS', 'BOXNS'), ('BCN', 'BCN'), ('BCNA', 'BCNA'), ('BCNAHS', 'BCNAHS'), ('BCCNR', 'BCCNR'), ('BTPN', 'BTPN'), ('BTPNHS', 'BTPNHS'), ('BTPGLN', 'BTPGLN'), ('BTALN', 'BTALN'), ('BTCS', 'BTCS'), ('BTPH', 'BTPH'), ('BTAP', 'BTAP'), ('BTFLN', 'BTFLN'), ('BRNA', 'BRNA'), ('BRNAHS', 'BRNAHS'), ('BFNS', 'BFNS'), ('BOMN', 'BOMN'), ('BRSTH', 'BRSTH'), ('BFAT', 'BFAT'), ('BLCA', 'BLCA'), ('BLCB', 'BLCB'), ('BLLA', 'BLLA'), ('BLLB', 'BLLB'), ('BRS', 'BRS'), ('BFU', 'BFU'), ('BRHNEHS', 'BRHNEHS'), ('BCL', 'BCL'), ('BCLA', 'BCLA'), ('BOBYN', 'BOBYN'), ('BOBYNHS', 'BOBYNHS'), ('BOBRN', 'BOBRN'), ('BOBRNHS', 'BOBRNHS'), ('BOBRAL', 'BOBRAL'), ('BOBSN', 'BOBSN'), ('BWTB', 'BWTB'), ('MBWT', 'MBWT'), ('DBKM', 'DBKM'), ('MBWZ', 'MBWZ'), ('BVZC', 'BVZC'), ('BVZI', 'BVZI'), ('BFKHN', 'BFKHN')], default='SelectWagon', max_length=11, null=True)),
                ('Wagon3Number', models.BigIntegerField(blank=True, null=True)),
                ('Wagon3Type', models.CharField(blank=True, choices=[('SelectWagon', 'Please Select Wagon Type'), ('BOXN', 'BOXN'), ('BOXNHA', 'BOXNHA'), ('BOXNHS', 'BOXNHS'), ('BOXNCR', 'BOXNCR'), ('BOXNLW', 'BOXNLW'), ('BOXNB', 'BOXNB'), ('BOXNF', 'BOXNF'), ('BOXNG', 'BOXNG'), ('BOY', 'BOY'), ('BOST', 'BOST'), ('BOXNAL', 'BOXNAL'), ('BOSTHS', 'BOSTHS'), ('BOXNHL', 'BOXNHL'), ('BOXNAL', 'BOXNAL'), ('BOXNS', 'BOXNS'), ('BCN', 'BCN'), ('BCNA', 'BCNA'), ('BCNAHS', 'BCNAHS'), ('BCCNR', 'BCCNR'), ('BTPN', 'BTPN'), ('BTPNHS', 'BTPNHS'), ('BTPGLN', 'BTPGLN'), ('BTALN', 'BTALN'), ('BTCS', 'BTCS'), ('BTPH', 'BTPH'), ('BTAP', 'BTAP'), ('BTFLN', 'BTFLN'), ('BRNA', 'BRNA'), ('BRNAHS', 'BRNAHS'), ('BFNS', 'BFNS'), ('BOMN', 'BOMN'), ('BRSTH', 'BRSTH'), ('BFAT', 'BFAT'), ('BLCA', 'BLCA'), ('BLCB', 'BLCB'), ('BLLA', 'BLLA'), ('BLLB', 'BLLB'), ('BRS', 'BRS'), ('BFU', 'BFU'), ('BRHNEHS', 'BRHNEHS'), ('BCL', 'BCL'), ('BCLA', 'BCLA'), ('BOBYN', 'BOBYN'), ('BOBYNHS', 'BOBYNHS'), ('BOBRN', 'BOBRN'), ('BOBRNHS', 'BOBRNHS'), ('BOBRAL', 'BOBRAL'), ('BOBSN', 'BOBSN'), ('BWTB', 'BWTB'), ('MBWT', 'MBWT'), ('DBKM', 'DBKM'), ('MBWZ', 'MBWZ'), ('BVZC', 'BVZC'), ('BVZI', 'BVZI'), ('BFKHN', 'BFKHN')], default='SelectWagon', max_length=11, null=True)),
                ('Wagon4Number', models.BigIntegerField(blank=True, null=True)),
                ('Wagon4Type', models.CharField(blank=True, choices=[('SelectWagon', 'Please Select Wagon Type'), ('BOXN', 'BOXN'), ('BOXNHA', 'BOXNHA'), ('BOXNHS', 'BOXNHS'), ('BOXNCR', 'BOXNCR'), ('BOXNLW', 'BOXNLW'), ('BOXNB', 'BOXNB'), ('BOXNF', 'BOXNF'), ('BOXNG', 'BOXNG'), ('BOY', 'BOY'), ('BOST', 'BOST'), ('BOXNAL', 'BOXNAL'), ('BOSTHS', 'BOSTHS'), ('BOXNHL', 'BOXNHL'), ('BOXNAL', 'BOXNAL'), ('BOXNS', 'BOXNS'), ('BCN', 'BCN'), ('BCNA', 'BCNA'), ('BCNAHS', 'BCNAHS'), ('BCCNR', 'BCCNR'), ('BTPN', 'BTPN'), ('BTPNHS', 'BTPNHS'), ('BTPGLN', 'BTPGLN'), ('BTALN', 'BTALN'), ('BTCS', 'BTCS'), ('BTPH', 'BTPH'), ('BTAP', 'BTAP'), ('BTFLN', 'BTFLN'), ('BRNA', 'BRNA'), ('BRNAHS', 'BRNAHS'), ('BFNS', 'BFNS'), ('BOMN', 'BOMN'), ('BRSTH', 'BRSTH'), ('BFAT', 'BFAT'), ('BLCA', 'BLCA'), ('BLCB', 'BLCB'), ('BLLA', 'BLLA'), ('BLLB', 'BLLB'), ('BRS', 'BRS'), ('BFU', 'BFU'), ('BRHNEHS', 'BRHNEHS'), ('BCL', 'BCL'), ('BCLA', 'BCLA'), ('BOBYN', 'BOBYN'), ('BOBYNHS', 'BOBYNHS'), ('BOBRN', 'BOBRN'), ('BOBRNHS', 'BOBRNHS'), ('BOBRAL', 'BOBRAL'), ('BOBSN', 'BOBSN'), ('BWTB', 'BWTB'), ('MBWT', 'MBWT'), ('DBKM', 'DBKM'), ('MBWZ', 'MBWZ'), ('BVZC', 'BVZC'), ('BVZI', 'BVZI'), ('BFKHN', 'BFKHN')], default='SelectWagon', max_length=11, null=True)),
                ('Wagon5Number', models.BigIntegerField(blank=True, null=True)),
                ('Wagon5Type', models.CharField(blank=True, choices=[('SelectWagon', 'Please Select Wagon Type'), ('BOXN', 'BOXN'), ('BOXNHA', 'BOXNHA'), ('BOXNHS', 'BOXNHS'), ('BOXNCR', 'BOXNCR'), ('BOXNLW', 'BOXNLW'), ('BOXNB', 'BOXNB'), ('BOXNF', 'BOXNF'), ('BOXNG', 'BOXNG'), ('BOY', 'BOY'), ('BOST', 'BOST'), ('BOXNAL', 'BOXNAL'), ('BOSTHS', 'BOSTHS'), ('BOXNHL', 'BOXNHL'), ('BOXNAL', 'BOXNAL'), ('BOXNS', 'BOXNS'), ('BCN', 'BCN'), ('BCNA', 'BCNA'), ('BCNAHS', 'BCNAHS'), ('BCCNR', 'BCCNR'), ('BTPN', 'BTPN'), ('BTPNHS', 'BTPNHS'), ('BTPGLN', 'BTPGLN'), ('BTALN', 'BTALN'), ('BTCS', 'BTCS'), ('BTPH', 'BTPH'), ('BTAP', 'BTAP'), ('BTFLN', 'BTFLN'), ('BRNA', 'BRNA'), ('BRNAHS', 'BRNAHS'), ('BFNS', 'BFNS'), ('BOMN', 'BOMN'), ('BRSTH', 'BRSTH'), ('BFAT', 'BFAT'), ('BLCA', 'BLCA'), ('BLCB', 'BLCB'), ('BLLA', 'BLLA'), ('BLLB', 'BLLB'), ('BRS', 'BRS'), ('BFU', 'BFU'), ('BRHNEHS', 'BRHNEHS'), ('BCL', 'BCL'), ('BCLA', 'BCLA'), ('BOBYN', 'BOBYN'), ('BOBYNHS', 'BOBYNHS'), ('BOBRN', 'BOBRN'), ('BOBRNHS', 'BOBRNHS'), ('BOBRAL', 'BOBRAL'), ('BOBSN', 'BOBSN'), ('BWTB', 'BWTB'), ('MBWT', 'MBWT'), ('DBKM', 'DBKM'), ('MBWZ', 'MBWZ'), ('BVZC', 'BVZC'), ('BVZI', 'BVZI'), ('BFKHN', 'BFKHN')], default='SelectWagon', max_length=11, null=True)),
                ('ModuleRecieveDate', models.DateField(default='1001-01-01', null=True)),
                ('ModuleCommDate', models.DateField(blank=True, default='1001-01-01', null=True)),
                ('ModuleROHDate', models.DateField(blank=True, default='1001-01-01', null=True)),
                ('ModulePOHDate', models.DateField(blank=True, default='1001-01-01', null=True)),
                ('Wagon1Defect', models.CharField(blank=True, max_length=100, null=True)),
                ('Wagon2Defect', models.CharField(blank=True, max_length=100, null=True)),
                ('Wagon3Defect', models.CharField(blank=True, max_length=100, null=True)),
                ('Wagon4Defect', models.CharField(blank=True, max_length=100, null=True)),
                ('Wagon5Defect', models.CharField(blank=True, max_length=100, null=True)),
                ('ModuleDVS', models.BooleanField(blank=True, default=False)),
                ('ModuleDVR', models.BooleanField(blank=True, default=False)),
                ('ModuleDVSDate', models.DateField(blank=True, null=True)),
                ('POHStation', models.CharField(blank=True, max_length=100, null=True)),
                ('ROHStation', models.CharField(blank=True, max_length=100, null=True)),
                ('ModulePresentPosition', models.CharField(choices=[('TKD_ROH1', 'TKD ROH 1'), ('TKD_ROH2', 'TKD ROH 2'), ('TKD_Sickline', 'TKD Sickline'), ('TKD_ACTL', 'TKD ACTL'), ('TKD_HTPP_PWL', 'TKD HTPP PWL'), ('TKD_ICD', 'TKD ICD'), ('TKD_YARD', 'TKD YARD'), ('SSB_ICD_GHH', 'SSB ICD GHH'), ('SSB_ICD_PT', 'SSB ICD PTT'), ('GZB_ICD_NOLI', 'GZB ICD NOLI'), ('GZB_ICD_MUZ', 'GZB ICD MUZ'), ('PNP_BMDJ', 'PNP BMDJ'), ('PNP_PCWD_DWNA', 'PNP PCWD DWNA')], default='YARD', max_length=13)),
                ('ModuleMadeFit', models.BooleanField(blank=True, default=False)),
                ('ModuleMadeFitDateTime', models.DateTimeField(blank=True, null=True)),
                ('ROHFile', models.FileField(blank=True, null=True, upload_to='ROH/%Y/%m/%d/')),
            ],
        ),
    ]
