# Generated by Django 3.2.6 on 2021-08-29 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rakes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rake',
            name='Module4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Mod4', to='rakes.module'),
        ),
        migrations.AddField(
            model_name='rake',
            name='Module5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Mod5', to='rakes.module'),
        ),
        migrations.AddField(
            model_name='rake',
            name='Module6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Mod6', to='rakes.module'),
        ),
        migrations.AddField(
            model_name='rake',
            name='Module7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Mod7', to='rakes.module'),
        ),
        migrations.AddField(
            model_name='rake',
            name='Module8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Mod8', to='rakes.module'),
        ),
        migrations.AddField(
            model_name='rake',
            name='Module9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Mod9', to='rakes.module'),
        ),
    ]
