# Generated by Django 3.2.6 on 2021-08-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rakes', '0002_auto_20210829_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rake',
            name='RakeName',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
