# Generated by Django 3.2.6 on 2021-09-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rakes', '0003_alter_rake_rakename'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='Modified',
            field=models.BooleanField(default=False),
        ),
    ]
