# Generated by Django 3.2.6 on 2021-09-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rakes', '0004_module_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='ModuleDVR',
        ),
        migrations.RemoveField(
            model_name='module',
            name='ModuleDVS',
        ),
        migrations.RemoveField(
            model_name='module',
            name='ModuleDVSDate',
        ),
        migrations.RemoveField(
            model_name='module',
            name='Wagon1Defect',
        ),
        migrations.RemoveField(
            model_name='module',
            name='Wagon1Type',
        ),
        migrations.RemoveField(
            model_name='module',
            name='Wagon2Defect',
        ),
        migrations.RemoveField(
            model_name='module',
            name='Wagon2Type',
        ),
        migrations.RemoveField(
            model_name='module',
            name='Wagon3Defect',
        ),
        migrations.RemoveField(
            model_name='module',
            name='Wagon3Type',
        ),
        migrations.RemoveField(
            model_name='module',
            name='Wagon4Defect',
        ),
        migrations.RemoveField(
            model_name='module',
            name='Wagon4Type',
        ),
        migrations.RemoveField(
            model_name='module',
            name='Wagon5Defect',
        ),
        migrations.RemoveField(
            model_name='module',
            name='Wagon5Type',
        ),
        migrations.AddField(
            model_name='module',
            name='ModuleType',
            field=models.CharField(blank=True, choices=[('SelectWagon', 'Please Select Wagon Type'), ('BLCA', 'BLCA'), ('BLCB', 'BLCB'), ('BLLA', 'BLLA'), ('BLLB', 'BLLB'), ('BLCMA', 'BLCMA'), ('BLCMB', 'BLCMB'), ('BVZC', 'BVZC'), ('BVZI', 'BVZI'), ('BFKHN', 'BFKHN')], default='SelectType', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='Modified',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
