# Generated by Django 3.2.6 on 2021-09-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rakes', '0005_auto_20210909_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='ModuleType',
            field=models.CharField(blank=True, choices=[('SelectWagon', 'Please Select Wagon Type'), ('BLC', 'BLC'), ('BLL', 'BLL'), ('BLCM', 'BLCM'), ('BVZC', 'BVZC'), ('BVZI', 'BVZI'), ('BFKHN', 'BFKHN')], default='SelectType', max_length=11, null=True),
        ),
    ]
