# Generated by Django 3.2.6 on 2021-09-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rakes', '0006_alter_module_moduletype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rake',
            name='RakeName',
            field=models.CharField(default='Error', max_length=100, unique=True),
        ),
    ]
