# Generated by Django 3.2.6 on 2021-09-10 17:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CCDDetails',
            fields=[
                ('Serial', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('RakeName', models.CharField(max_length=50, null=True)),
                ('ExamPlace', models.CharField(blank=True, choices=[('TKD_ACTL', 'TKD ACTL'), ('TKD_HTPP_PWL', 'TKD HTPP PWL'), ('TKD_ICD', 'TKD ICD'), ('TKD_YARD', 'TKD YARD')], default='TKD YARD', max_length=13, null=True)),
                ('TKDInTime', models.DateTimeField(null=True)),
                ('TKDOutTime', models.DateTimeField(null=True)),
                ('YardInTime', models.DateTimeField(null=True)),
                ('YardOutTime', models.DateTimeField(null=True)),
                ('SidingIn', models.DateTimeField(null=True)),
                ('SidingOut', models.DateTimeField(null=True)),
                ('UnloadingStart', models.DateTimeField(null=True)),
                ('UnloadingEnd', models.DateTimeField(null=True)),
                ('LoadingStart', models.DateTimeField(null=True)),
                ('LoadingEnd', models.DateTimeField(null=True)),
                ('T431IssueTime', models.DateTimeField(null=True)),
                ('T431ReceiveTime', models.DateTimeField(null=True)),
                ('WorkStart', models.DateTimeField(null=True)),
                ('WorkEnd', models.DateTimeField(null=True)),
                ('BrakeBlock', models.IntegerField(null=True)),
                ('Empad', models.IntegerField(null=True)),
                ('AdopterChanged', models.IntegerField(null=True)),
                ('AdopterCantt', models.IntegerField(null=True)),
                ('SideBearerSpring', models.IntegerField(null=True)),
                ('JawLinerWeld', models.IntegerField(null=True)),
                ('ATLRepair', models.IntegerField(null=True)),
                ('ROHDetachment', models.IntegerField(null=True)),
                ('POHDetachment', models.IntegerField(null=True)),
                ('DVSDetachment', models.IntegerField(null=True)),
                ('TrafficDetention', models.TimeField(null=True)),
                ('SidingDetention', models.TimeField(null=True)),
                ('MechanicalDetention', models.TimeField(null=True)),
                ('NewBPCNumber', models.BigIntegerField(null=True)),
                ('NewBPCDate', models.DateField(null=True)),
                ('OldBPCNumber', models.BigIntegerField(null=True)),
                ('OldBPCDate', models.DateField(null=True)),
            ],
        ),
    ]
