# Generated by Django 3.2.6 on 2021-09-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_rename_ccddetails_ccdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccdetails',
            name='ATLRepair',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ccdetails',
            name='AdopterCantt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ccdetails',
            name='AdopterChanged',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ccdetails',
            name='BrakeBlock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ccdetails',
            name='DVSDetachment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ccdetails',
            name='Empad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ccdetails',
            name='ExamDetails',
            field=models.BooleanField(blank=True, default='False'),
        ),
        migrations.AlterField(
            model_name='ccdetails',
            name='JawLinerWeld',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ccdetails',
            name='LoadingEnd',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ccdetails',
            name='LoadingStart',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ccdetails',
            name='MechanicalDetention',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ccdetails',
            name='NewBPCDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ccdetails',
            name='NewBPCNumber',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ccdetails',
            name='OldBPCDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ccdetails',
            name='OldBPCNumber',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ccdetails',
            name='POHDetachment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ccdetails',
            name='PostExamDetails',
            field=models.BooleanField(blank=True, default='False'),
        ),
        migrations.AlterField(
            model_name='ccdetails',
            name='PreExamDetails',
            field=models.BooleanField(blank=True, default='False'),
        ),
        migrations.AlterField(
            model_name='ccdetails',
            name='ROHDetachment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ccdetails',
            name='SideBearerSpring',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ccdetails',
            name='SidingDetention',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ccdetails',
            name='SidingIn',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ccdetails',
            name='SidingOut',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ccdetails',
            name='T431IssueTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ccdetails',
            name='T431ReceiveTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ccdetails',
            name='TKDInTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ccdetails',
            name='TKDOutTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ccdetails',
            name='TrafficDetention',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ccdetails',
            name='UnloadingEnd',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ccdetails',
            name='UnloadingStart',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ccdetails',
            name='WorkEnd',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ccdetails',
            name='WorkStart',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ccdetails',
            name='YardInTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ccdetails',
            name='YardOutTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
