# Generated by Django 3.2.6 on 2021-09-16 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0005_ccdetails_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccdetails',
            name='examauthor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examccid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ccdetails',
            name='postexamauthor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postexamccid', to=settings.AUTH_USER_MODEL),
        ),
    ]
