# Generated by Django 3.2.6 on 2021-09-16 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rakes', '0007_alter_rake_rakename'),
        ('exams', '0006_auto_20210916_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccdetails',
            name='RakeName',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.PROTECT, related_name='vcomments', to='rakes.rake'),
        ),
    ]
